article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addarticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('edit/<int:id>',views.edit,name="edit"),
    path('delete/<int:id>',views.delete,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"), #url is mapped to view, we can name urls using name attribute
    path('about/', views.about, name = "about"),
    path('detail/<int:id>', views.detail, name = "detail"),
    path('articles/',include("article.urls") ),
    path('user/',include("user.urls") ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loging,name="login"),
    path('logout/',views.logingout,name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE) # usingon-delete parameter makes auto-deletion of articles that user created when user is deleted
    title = models.CharField(max_length = 50)
    content = RichTextField(verbose_name= "Article Content") # If we use verbose_name parameter, in admin panel, we see the title as given text
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Creation Date")
    article_image = models.FileField(blank = True, null = True, verbose_name="Add an image")
    def __str__(self): #To make article title seen on admin panel
        return(self.title)
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name ="Article",related_name="comments")
    comment_author = models.CharField(max_length=30,verbose_name="author")
    comment_content = models.CharField(max_length=300,verbose_name="content")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self): 
        return(self.comment_content)
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','content','article_image']
    

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, label="Username")
    password = forms.CharField(min_length=6,max_length=50,label="Password", widget=forms.PasswordInput)
    
class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, label="Username")
    password = forms.CharField(min_length=6,max_length=50,label="Password", widget=forms.PasswordInput)
    confirm = forms.CharField(min_length=6,max_length=50,label="Confirm Password", widget=forms.PasswordInput)
    def clean(self):
        username=self.cleaned_data.get("username")
        password=self.cleaned_data.get("password")
        confirm=self.cleaned_data.get("confirm")
        if password and confirm and password !=confirm:
            raise forms.ValidationError("Passwords doesn't match")
        values = {
            "username":username,
            "password":password
        }
        return values

article/views.py
from django.shortcuts import render, reverse, redirect,HttpResponse,get_object_or_404
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.


def articles(request):
    keyword = request.GET.get("keyword")
    if  not keyword:
        articles = Article.objects.all()
        context={
            "articles":articles
        }
        return render(request,"articles.html",context)
    else:
        articles = Article.objects.filter(content__contains = keyword)
        context={
            "articles":articles
        }
        return render(request,"articles.html",context)


def index(request):

    return render(request,"index.html")

def about(request):

    return render(request,"about.html")

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Article successfully added")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{"form":form})

def detail(request,id):   
    #article=Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id=id)

    comments=article.comments.all()

    return render(request,"detail.html",{"article":article, "comments":comments})

@login_required(login_url = "user:login")
def edit(request,id):
    article= get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Article successfully updated")
        return redirect("article:dashboard")
    else:
        return render(request,"edit.html",{"form":form})
    
    
@login_required(login_url = "user:login")
def delete(request,id):
    article= get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Article successfully deleted")
    return redirect("article:dashboard")


def addComment(request,id):
    article =get_object_or_404(Article,id=id)

    if request.method=="POST":
        comment_author=request.POST.get("comment_author")
        comment_content=request.POST.get("comment_content")
        comment=Comment(comment_author=comment_author,comment_content=comment_content)
        comment.article=article
        comment.save()
        messages.success(request,"Your comment is successfully added")
    # return redirect("detail",str(id)) it works
    return redirect(reverse("article:detail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages


# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None)

    if form.is_valid(): #calls clean method from RegisterForm
        
        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password") 
        
        user=User(username=username)
        user.set_password(password)
        
        user.save()
        login(request,user)
        messages.success(request,"You are registered successfully")
        
        return redirect("index")
    context ={"form" : form}
    return render(request,"register.html",context)
    
def loging(request):

    form = LoginForm(request.POST or None)
    context = {"form":form}

    if form.is_valid():
        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password")
        user =authenticate(username=username, password=password)

        if user is None:
            messages.info(request,"Wrong password or username")
            return render(request,"login.html",context)

        messages.success(request,"Successfully logged in")
        login(request,user)
        return redirect("index")

    return render(request, "login.html",context)

def logingout(request):
    logout(request)
    messages.success(request,"Successfully logged out")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}


{% block body %}
    <h3>ABOUT US<h3>
    <hr>
    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
{% endblock body %} 

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    <div class="row justify-content-md-center">
    <h3>ADD ARTICLE</h3>
    </div>
    <div class="row justify-content-md-center">
        

        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form |crispy}} <!-- to use crispy forms -->
            <br>
            <button type="submit" class="btn btn-primary">Add Article</button>
        </form>
    </div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
    <div class="row">
        <div class="col-lg-8">
            <h3>ARTICLES</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <form>
                {% csrf_token %}
                <input type="text" class="input-sm" name="keyword" maxlength="64" placeholder="Search in Articles">
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
    </div>
{% if articles %}

    <hr>
    {% for article in articles  %}
        <div class="row">

            <!-- Post Content Column -->
            <div class="col-lg-8">

                <!-- Title -->
                <h1 class="mt-4"><a href="{%url 'article:detail' article.id%}">{{article.title}}</a></h1>

                <!-- Author -->
                <p class="lead">by {{article.author}}</p>
                <hr>

                <!-- Date/Time -->
                <p>Posted On : {{article.created_date}}</p>

                <hr>

                <!-- Preview Image -->
                {% if article.article_image %}
                <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">

                {% else %}
                {% endif %}
                
                <hr>
                <p>
                    {{article.content|safe|truncatewords:30 }}
                    <br>
                    <a style="float : right" href="{%url 'article:detail' article.id%}"><button type="submit" class="btn btn-primary">Read more</button></a>
                    <br>
                </p>
                <hr>
            </div>
        </div>

    {% endfor %}
        </table>
{% else %}
<div class="alert alert-danger">
    No article has been found...
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}


{% block body %}
    <h3></h3>
    <hr>
    <p>
        <small>Welcome {{request.user.username}}</small>
    </p>
    <hr>
    {% if articles %}

        <table class="table table-hover">
        <thead>
            <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Created On</th>
            <th scope="col"></th>
            <th scope="col"></th>
            </tr>
        </thead>
            {% for article in articles  %}
                <tbody>
                    <tr>
                    <th scope="row">{{article.id}}</th>
                    <td><a href="{%url 'article:detail' article.id%}">{{article.title}}</a></td>
                    <td>{{article.author}}</td>
                    <td>{{article.created_date}}</td>
                    <td> <a href="{%url 'article:edit' article.id%}" type="button" class="alert alert-info">Edit</a></td>
                    <td> <a href="{%url 'article:delete' article.id%}" type="button" class="alert alert-danger">Delete</a></td>
                    </tr>
                </tbody>

            {% endfor %}
        </table>

        {% else %}
        <div class="alert alert-info">
            You have not contribited to article database yet.
        </div>
    {% endif %}

    <a class ="btn btn-danger" href="{%url 'article:addarticle'%}">Add Article</a>




{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{article.title}}</h1>

        <!-- Author -->
        <p class="lead">by {{article.author}}</p>
        <hr>

        <!-- Date/Time -->
        <p>Posted On : {{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
          <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">

        {% else %}
        {% endif %}
        
        <hr>
            {{article.content|safe}}
        <hr>

        {% if comments %}

          {% for comment in comments %}
            <div class="media mb-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">{{comment.comment_author}}</h5>
                {{comment.comment_content}}
                <br>
                <div style="float : right">
                  Creation Date: {{comment.comment_date}}
                </div>
              </div>
            </div>
          {% endfor %}
          
        {% else %}
        <div class="alert alert-info">
           There is no comment yet...
        </div>
        {% endif %}




            <!-- Post Content Column -->
            <div class="card my-4">
              <h5 class="card-header">Leave a Comment:</h5>
              <div class="card-body">
                <form action = "{%url 'article:comment' article.id%}" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="formGroupExampleInput">Name</label>
                    <input type="text" name="comment_author" class="form-control" id="formGroupExampleInput" placeholder="Example input">
                  </div>
                  <div class="form-group">
                    <label for="formGroupExampleInput">Comment</label>
                    <textarea name="comment_content" class="form-control" rows="3"></textarea>
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
              </div>
            </div>
      </div>

{% endblock body %}

templates/edit.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
    <div class="row justify-content-md-center">
    <h3>UPDATE ARTICLE</h3>
    </div>
    <div class="row justify-content-md-center">
        

        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form |crispy}} <!-- to use crispy forms -->
            <br>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>

{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{%url 'index'%}">MY BLOG</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'about'%}">About </span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'article:articles'%}">Articles </span></a>
          </li>
        </ul>      

        <ul class="navbar-nav ml-auto">

        {% if request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'article:dashboard'%}">Dashboard </span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'user:logout'%}">Log out </span></a>
          </li>
        {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'user:register'%}">Register </span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'user:login'%}">Login </span></a>
          </li>
        {% endif %}

          

          
    
        </ul>
      </div>
    </nav>

templates/includes/posttamplates.html
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>

templates/index.html
{% extends "layout.html" %}

{% block body %}
    <div class ="jumbotron text-center">
        <h3>Welcome To My Blog</h3>
        <p>This is my first blog</p>
    </div>
    {% if request.user.is_authenticated %}
        User Authenticated : {{request.user.username}}
    {% else %}
        User NOT Authenticated
    {% endif %}
   
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <title>My Blog</title>
</head>
<body>
    {% include "includes/navbar.html" %}
    
    <div style="margin-top: 70px; margin-bottom: 100px" class="container">
    {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
        {% block body  %}
        
        {% endblock body  %}
    </div>


    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js'  %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>


</pre>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row justify-content-md-center">
    <h3>LOG IN</h3>
</div>

<div class="row justify-content-md-center">
    <form method = "post">
        {% csrf_token %}
        {{form |crispy}} <!-- as_p is to show form on screen -->
        <br>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
    
    

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %},
<div class="row justify-content-md-center">
    <h3>REGISTER</h3>
</div>
<div class="row justify-content-md-center">
    <form method = "post">
        {% csrf_token %}
        {{form|crispy}} <!-- as_p is to show form on screen -->
        <br>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>

    
    


{% endblock body %}